info:
  name: list-tasks
  type: http
  seq: 1

http:
  method: GET
  url: "{{baseUrl}}/projects/:id/tasks"
  params:
    - name: id
      value: "1"
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
