info:
  name: update-task-priority
  type: http
  seq: 6

http:
  method: PATCH
  url: "{{baseUrl}}/tasks/:id"
  params:
    - name: id
      value: "{{taskId}}"
      type: path
  body:
    type: json
    data: |-
      {
        "priority": "low"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false
