name: Local
variables:
  - name: baseUrl
    value: localhost:3000
  - name: accessToken
    secret: true
    type: string
  - name: refreshToken
    secret: true
    type: string
  - name: secondUserAccessToken
    secret: true
    type: string
